### ISSUE TITLE
main.ts

### ISSUE THREAD

**Issue by baguosiji** [PeterStaev/nativescript-image-swipe#11]
Argument type ()=>ImageSwipe is not assignable to parameter type ViewResolve[
![2_3in h m ale328xpzov](https://user-images.githubusercontent.com/27269213/27417285-d4e80896-5745-11e7-8000-c8b075a2d9b5.png)
](url)

**Comment by baguosiji** [comment]
This is my package.json

**Comment by baguosiji** [comment]
This is my package.json
![Uploading 9)TWG2JP_02YQ[`]E}T8Y[F.png…]()

**Comment by baguosiji** [comment]
This is my package.json[](url)
![9 twg2jp_02yq e t8y f](https://user-images.githubusercontent.com/27269213/27417774-5d1403ca-5749-11e7-8214-42938d405b9a.png)

**Comment by PeterStaev** [comment]
Hey @baguosiji , the `demo-ng` project in the repo contains a fully working demo for Angular with the latest version of the plugin and TNS runtime. I suggest you start from there and try to isolate your problem.

**Comment by baguosiji** [comment]
@PeterStaev  Hi PeterStaev thank you very much for your reply, I found my question.
The compiler no recognition ImageSwip

**Comment by PeterStaev** [comment]
@baguosiji , does this mean that you have your problem resolved? If so then I guess we can close this one?

**Comment by baguosiji** [comment]
@PeterStaev  Yes my problem solved, can be closed
