### ISSUE TITLE
Failure to load first image

### ISSUE THREAD

**Issue by zprice-invsqr** [PeterStaev/nativescript-image-swipe#13]
When the initial value of `pageNumber` is set to 0, the first image fails to load (e.g. a blank/empty screen is shown). This was confirmed across two projects and is reproducible with the Angular example code by setting `pageNumber` to 0 instead of 3.

Edit: Sorry, I forgot to mention this was tested only in an iOS simulator.

**Comment by jessebacon** [comment]
Any movement on this @PeterStaev? I'd be happy to dig in and take a look if I got some direction on the best place to start.

**Comment by PeterStaev** [comment]
@jessebacon , I am a bit swamped with work on other projects, so sadly I haven't done any tracing on this. Sadly I cannot give you any directions since I do not know what/where is the problem. I have the plugin working in a non-angular app even with the first page, so it could be something with the angular code, not sure.

**Comment by jessebacon** [comment]
Thanks for a quick response @PeterStaev! Given that, I might try to check it's a zone issue with angular.

**Comment by omaralsoudanii** [comment]
Any fix for this ? I got it too.

**Comment by OPADA-Eng** [comment]
I fixed this by using **ObservableArray** and setting `pageNumber="0"`.

**Comment by VladimirAmiorkov** [comment]
In my project I use ObservableArray and this issue persists.

**Comment by PeterStaev** [comment]
@VladimirAmiorkov , can you provide a peroducable example in the playground? I'm actively using this plugin in couple of apps and never had problems with it.

**Comment by VladimirAmiorkov** [comment]
Hi @PeterStaev ,

Yes I will try to provide a sample.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
