### ISSUE TITLE
how to display image file from local storage?

### ISSUE THREAD

**Issue by wiliarko** [PeterStaev/nativescript-image-swipe#19]
how to display image file from local storage?

i can't display image from local storage.

System.err: java.net.MalformedURLException: Protocol not found: ~/storage/emulated/0/DCIM/Camera/NSIMG_20171027_52440.jpg

**Comment by PeterStaev** [comment]
Hey @wiliarko , behind the scenes the plugin uses NativeScript's [ImageCache](https://docs.nativescript.org/cookbook/ui/image-cache) module which works with URLs. So you need to use a URL and not file path (something like `file://........`).

**Comment by wiliarko** [comment]
thanks @PeterStaev it's work for me

**Comment by Archi20** [comment]
Any more tips for this? I can't resolve similar issue :(

components.ts
`	
mapPath: string = "~/assets/images/" + environment.mapName;
items: any[] = [];


	ngOnInit() { 
		this.items.push({ file: this.mapPath });
	}
`

.html
` 
<GridLayout class="main">
 <ImageSwipe  [items]="items" imageUrlProperty="imageUrl"></ImageSwipe>
</GridLayout>
`

For Random Url works fine, bu i need get image from file, any help?

**Comment by PeterStaev** [comment]
@Archi20 , see my comment above. This should be a **URL** not a path.

**Comment by Archi20** [comment]
So it is impossible to use file-path with this plugin?

**Comment by PeterStaev** [comment]
You need to transform the file-path to file-url. Again see my first comment here. You can see what NS core class the plugin uses and in turn what that class supports.

**Comment by sepccom** [comment]
@PeterStaev are you able to provide an example using file://

For example, I am saving the edited image to **/data/user/0/au.com.sepccom.pl/files/5628_updated.png**

How do I push this back to the viewModel imageUrl field so that the existing image is replaced with the edited version?

Thanks,

**Comment by PeterStaev** [comment]
@sepccom , your url should look as any other file Url in nativecsript:
```
 file:///data/user/0/au.com.sepccom.pl/files/5628_updated.png
```

Also providing user specific examples is not part of the free support of this plugin. If you wish we offer paid support for all of my plugins and you can buy one here: https://www.tangrainc.com/subscriptions/
