### ISSUE TITLE
Support content like titles (Labels)

### ISSUE THREAD

**Issue by jdnichollsc** [PeterStaev/nativescript-image-swipe#20]
Thanks for this excellent plugin, it's really awesome!
One question, Is possible to support labels like titles of each image?

Thanks in advance

**Comment by PeterStaev** [comment]
Hey @jdnichollsc , the plugin only shows the images and it does not support adding anything else. If you want to add some labels you will have to add those in your app, and then listen on the `pageChanged` event of the plugin and update the title.
