### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by seetharamiah** [PeterStaev/nativescript-image-swipe#31]

**Comment by seetharamiah** [comment]
bug,help wanted

**Comment by PeterStaev** [comment]
Hey @seetharamiah , w/o any further details, this does not make much sense to me.

**Comment by seetharamiah** [comment]
System.err: java.net.ProtocolException: unexpected end of stream
System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:747)
System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:761)
System.err:     at org.nativescript.widgets.Async$Image$DownloadImageTask.doInBackground(Async.java:171)
System.err:     at org.nativescript.widgets.Async$Image$4.run(Async.java:147)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
System.err:     at org.nativescript.widgets.Async$PriorityThreadFactory$1.run(Async.java:53)
System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by seetharamiah** [comment]
while swiping images , i got this error

**Comment by PeterStaev** [comment]
Seems the URLs you provided are not valid or are not Bitmaps. Please verify that you can open the links in the phones browser.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
