### ISSUE TITLE
ERROR TypeError: Cannot read property 'getAdapter' of undefined

### ISSUE THREAD

**Issue by anandmt70** [PeterStaev/nativescript-image-swipe#36]
while loading for the first time this error message shown
ERROR TypeError: Cannot read property 'getAdapter' of undefined
how to fix it.?

**Comment by PeterStaev** [comment]
Hey @anandmt70 , please provide more details, what platform? Angular or plain nativescript? Also please refer to the demo projects in the repo, and if you still have problems provide a reproducible sample via the NativeScript Playground.

**Comment by anandmt70** [comment]
> Hey @anandmt70 , please provide more details, what platform? Angular or plain nativescript? Also please refer to the demo projects in the repo, and if you still have problems provide a reproducible sample via the NativeScript Playground.

native script angular

**Comment by Cayan** [comment]
I also have this issue with nativescript angular

**Comment by bachras** [comment]
Same issue on Android with nativescript Angular (5.3), latest plugin version(4.1.0). https://github.com/PeterStaev/nativescript-image-swipe/issues/38

**Comment by PeterStaev** [comment]
Hey guys, this should be resolved with the new version on npm (4.1.1)
