### ISSUE TITLE
Plain Nativescript (Pure Javascript) usage demo or example in documentation

### ISSUE THREAD

**Issue by marcelbonfim182** [PeterStaev/nativescript-image-swipe#37]
I installed the plugin and tried to run the following code in plain nativescript (pure javascript), but only black screen appears.

`const Observable = require ("tns-core-modules/data/observable").Observable;
const ObservableArray = require("tns-core-modules/data/observable-array").ObservableArray;
const Page = require("tns-core-modules/ui/page").Page;

const PageChangeEventData = require ("nativescript-image-swipe");`

`function onNavigatingTo(args) {
    page = args.object;
    page.bindingContext = new GaleriadeimagensViewModel();
	
	
	items = new ObservableArray(items);
		
	items = [ 
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
        {
			mageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"        },
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
		{
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        },
        {
			imageUrl: "http://www.mesmeracomunicacao.com.br/wp-content/uploads/2014/09/Delta-Rock-in-Rio.jpg"
        }];
		
	items = new ObservableArray(items);
		

	viewModel = new Observable();
    viewModel.set("items", items);
    viewModel.set("pageNumber", 3);
	

	page.bindingContext = viewModel;
}

exports.onNavigatingTo = onNavigatingTo;`

`<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:is="nativescript-image-swipe" navigatingTo="navigatingTo" loaded="onPageLoaded" actionBarHidden="true">
    <GridLayout>
        <is:ImageSwipe items="{{ items }}" imageUrlProperty="imageUrl" 
                       pageNumber="{{ pageNumber }}" pageChanged="pageChanged" backgroundColor="#000000" row="0" col="0" >
        </is:ImageSwipe>
    </GridLayout>
</Page>`

**Comment by PeterStaev** [comment]
Hey @marcelbonfim182 , your code is a total mess. You are double setting the `bindingContext`, you have bound some events that are not present in your code. 

Here is a running sample of your code with cleaned up things: https://play.nativescript.org/?template=play-js&id=6b8vGd

For future please refer to the demo projects in the repo and the readme in order to understand how the plugin is to be used. Those are there for a reason!

**Comment by marcelbonfim182** [comment]
Hello, it worked perfectly now! Thank you very much for your support!
