### ISSUE TITLE
Not ready for Nativescript 3

### ISSUE THREAD

**Issue by marcbuils** [PeterStaev/nativescript-image-swipe#4]
Hi PeterStaev,

Thank you very much for your plugin ;)
But I tried it with Nativescript 3 on my project, and I have the following error :

```bash
JS: TypeError: Could not load view for: ImageSwipe.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
```

I think it's because 'ui/core/proxy' doesn't exist in Nativescript 3, but I don't know develop in native Nativescript, so may be it's not the problem.

Best Regards,
Marc

**Comment by PeterStaev** [comment]
Hey @marcbuils , the plugin currently does not support NS 3.0. I have plans to upgrade it, but currently I cannot commit to a specific timeframe.

**Comment by buuhuu** [comment]
Really cool plugin. Will use it in my project as well and did the (unfortunately quick and dirty due to timely pressure) upgrade to NS 3.0. Its working well with nativescript-angular so far.
