### ISSUE TITLE
Plugin breaks after updating to {N} 6

### ISSUE THREAD

**Issue by hermandinho** [PeterStaev/nativescript-image-swipe#45]
Hello guys and thkans for the great plugin. Every things was working for {N} 5.4. But when i migrated to {N} 6.0, i receive this error during build

`Exception in thread "main" java.lang.RuntimeException: Class not found android.support.v4.view.ViewPager.OnPageChangeListener at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549) at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532) at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283) at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171) at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234) at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121) at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97) at org.nativescript.staticbindinggenerator.Main.main(Main.java:50)`

is there a solution for that?

**Comment by PeterStaev** [comment]
Hey @hermandinho , the fix for this is available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by adilsaeed31** [comment]
@PeterStaev I am trying to install this plugin but it's not downloading for me?

**Comment by PeterStaev** [comment]
@adilsaeed31 , have you subscribed to the service and logged in to the custom npm registry?

**Comment by adilsaeed31** [comment]
@PeterStaev I have logged in but didn't go for the subscription I want to test this plugin as per my requirement.

**Comment by PeterStaev** [comment]
@adilsaeed31 you cannot access the plugin w/o an active subscription. You can use the current version of the plugin with NS 5.x if you want to try it out w/o subscribing.

**Comment by adilsaeed31** [comment]
@adilsaeed31 I can't use this I've already updated my NS to 6.

**Comment by PeterStaev** [comment]
Well then there is no other option - the NS 6 support for this plugin is available only under the ProPlugins subscription. So the only options are you either pull the code and make the required changes yourself, or subscribe to the program.

**Comment by adilsaeed31** [comment]
@PeterStaev Give me some idea how I can do it I'm totally new with nativescript and nativescript plugin development
