### ISSUE TITLE
IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128

### ISSUE THREAD

**Issue by chinnapandian** [PeterStaev/nativescript-image-swipe#53]
Hi, If I keep swiping the image(s) back and forth, I get this exception
**IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128** 
any idea please?

Here is the snippets of the exceptions
10-24 13:19:29.879  9927  9927 W System.err: Calling js method instantiateItem failed
10-24 13:19:29.879  9927  9927 W System.err: Error: java.lang.IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128
10-24 13:19:29.879  9927  9927 W System.err:     android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:197)
10-24 13:19:29.879  9927  9927 W System.err:     android.hardware.SensorManager.registerListener(SensorManager.java:859)
10-24 13:19:29.879  9927  9927 W System.err:     android.hardware.SensorManager.registerListener(SensorManager.java:766)
10-24 13:19:29.879  9927  9927 W System.err:     android.view.OrientationEventListener.enable(OrientationEventListener.java:93)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1083)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1063)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1055)
10-24 13:19:29.879  9927  9927 W System.err:     com.tns.gen.androidx.viewpager.widget.PagerAdapter_vendor_92817_28_ImageSwipePageAdapter.instantiateItem(PagerAdapter_vendor_92817_28_ImageSwipePageAdapter.java:31)
10-24 13:19:29.879  9927  9927 W System.err:     androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
10-24 13:19:29.879  9927  9927 W System.err:     androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1192)
10-24 13:19:29.879  9927  9927 W System.err:     androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
10-24 13:19:29.879  9927  9927 W System.err:     androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
10-24 13:19:29.879  9927  9927 W System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
10-24 13:19:29.879  9927  9927 W System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:764)
10-24 13:19:29.880  9927  9927 W System.err:     android.view.Choreographer.doFrame(Choreographer.java:696)
10-24 13:19:29.880  9927  9927 W System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
10-24 13:19:29.880  9927  9927 W System.err:     android.os.Handler.handleCallback(Handler.java:873)
10-24 13:19:29.880  9927  9927 W System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
10-24 13:19:29.880  9927  9927 W System.err:     android.os.Looper.loop(Looper.java:214)
10-24 13:19:29.880  9927  9927 W System.err:     android.app.ActivityThread.main(ActivityThread.java:7099)
10-24 13:19:29.880  9927  9927 W System.err:     java.lang.reflect.Method.invoke(Native Method)
10-24 13:19:29.880  9927  9927 W System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-24 13:19:29.880  9927  9927 W System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by PeterStaev** [comment]
This should be fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
