### ISSUE TITLE
Pinch zoom on Android has an invalid center offset

### ISSUE THREAD

**Issue by hsluis** [PeterStaev/nativescript-image-swipe#54]
Hi,

I used this plugin (5.0.1) in a Nativescript-vue project with Nativescript 6.1.2 (Android).

On iOS everything is working perfectly, but on Android pinch zooming isn't responding as it should. However I zoom in, the image keeps sticking to the left part of the screen instead of having a center offset (between the fingers).

I use the component as follows:
```
<GridLayout>
        <ImageSwipe :items="items" imageUrlProperty="url" pageNumber="0"></ImageSwipe>
</GridLayout>
```
And in my main.ts I require the plugin like this:
```
Vue.registerElement("ImageSwipe", () => require("nativescript-image-swipe/image-swipe").ImageSwipe)
```

**Comment by jacopo69** [comment]
same behavior for me (plugin version 5.0.1 and NS 6.2.0)

**Comment by bonkboykz** [comment]
Hey, guys!

I had the same issue, but I just needed the image zoom functionality.

You could take look at https://github.com/abhayastudios/native-script-pan-scale-demo to implement something simillar

**Comment by PeterStaev** [comment]
This is now fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by miladfm** [comment]
I just subscribe to ProPlugins but pinch zoom still has invalid center offset.

It is version of plugin in the package.json

`"@proplugins/nativescript-image-swipe": "^7.0.0",`

**Comment by PeterStaev** [comment]
Hey @miladfm , I've just tried this on the emulator and from what I see it is working. Sadly dont have an android device on which i can test right now.

**Comment by miladfm** [comment]
I test it again on the emulator (Pixel-ea-API_30_x86 - Android 11) and the real device (Asus X00AD - Android 6.0.1).

But there are two problems.
1- Center offset of pinch-zoom: My finger is the center of the image, and I try to pinch it. But the offset of zoom is left of the picture.
2- movement after zoom: Image doesn't follow my finger during pan event (After zoom, I try to move picture but image move faster than my finger)

See this video https://youtu.be/tXUZ2yuvKAA

1-Zoom: My fingers are at the center of the image
2-Move: I move my finger just a little (maybe 10 DIPs), but the image move 3 or 4 times faster than my finger
