### ISSUE TITLE
Can I clear image cache? 

### ISSUE THREAD

**Issue by sroy93** [PeterStaev/nativescript-image-swipe#55]
Is there a way to clear the image cache at some point in code so that if an image changes, but keeps the same url, the image-swipe component will update? Or update the image that is saved in the image cache maybe? Something to that effect..

**Comment by PeterStaev** [comment]
Hey @sroy93 , currently there is no built-in way, but you can just append a random query string to the URL and this will cause the image to be re-cached.

**Comment by sroy93** [comment]
Oh okay. So you mean even if the URL of the image itself doesn't change, you could put 
"?somethingrandom=somethingrandom" at the end of the URL each time the image itself updates?

**Comment by sroy93** [comment]
I'm adding "?recache=" + Math.random();  to the URL property each time the image is retaken and it is working perfectly. If you saw my message about it not working, I deleted it because I had some additional things I had to add on my end to make it work for my code, but it is working. Thanks so much!!

**Comment by PeterStaev** [comment]
Just a quick follow up - clearing the cache or removing a specific image from it is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by sroy93** [comment]
I do subscribe already, I just am not using that version because of Progress having issues connecting to their NPM servers and not being able to build apps via NativeScript Sidekick with them included. But, as soon as they get that solved, that is where I will go for updates. Thank you for the follow up!
