### ISSUE TITLE
NativeScript 7 doesn't work.

### ISSUE THREAD

**Issue by pattrawuth2530** [PeterStaev/nativescript-image-swipe#59]
NativeScript 7 doesn't work.
I got error like this : 
Module 'nativescript-image-swipe' not found for element 'nativescript-image-swipe:ImageSwipe'.
Class constructor ScrollView cannot be invoked without 'new'

**Comment by PeterStaev** [comment]
Hey @pattrawuth2530 , per the note of the readme all future upgrades of the plugin will be available as part of [ProPlugins](https://proplugins.org/subscribe.html). There is already an NS7 compatible version there. If you cannot subscribe, then the only other option is for you to fork the code and make it compatible with NS7.
